services:
  backend:
    build: ./backend
    container_name: coobe-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: coobe-frontend
    ports:
      - "80:80"

  db:
    image: postgres:15
    container_name: coobe-db
    restart: always
    environment:
      POSTGRES_USER: coobe
      POSTGRES_PASSWORD: coobe
      POSTGRES_DB: coobe
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: