version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: coobe
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: coobe
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://coobe:secret@db:5432/coobe?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  db_data:
